#!/usr/bin/env bash
#===============================================================================
# generate-artifact.sh
#
# Generates and stores a markdown artifact in the appropriate persona directory.
# Designed to be called by persona agents (Dev, Research Analyst, Financial Analyst,
# Operations Manager) when producing valuable persisted outputs.
#
# Usage:
#   ./generate-artifact.sh <persona> <title> <content_file>
#
#   <persona>      — One of: research-analyst, financial-analyst, dev, operations-manager
#   <title>        — Human-readable title (used for the H1 and filename derivation)
#   <content_file> — Path to a file containing the markdown body (or "-" for stdin)
#
# Environment:
#   ARTIFACTS_DIR  — Override the root artifacts directory (default: ../artifacts)
#   SOURCES        — Optional comma-separated list of sources/URLs
#   EXECUTIVE_SUMMARY — Optional executive summary text (default: placeholder)
#   AUTHOR         — Persona or agent name (default: derived from <persona>)
#
# Examples:
#   echo "# My Report\n\nContent..." > /tmp/report.md
#   ./generate-artifact.sh research-analyst "DeepSeek Provider Analysis" /tmp/report.md
#
#   echo "Research content" | ./generate-artifact.sh dev "API Design" -
#
# Output:
#   Prints the artifact path on success. Exits non-zero on failure.
#===============================================================================

set -euo pipefail

# ── Configuration ────────────────────────────────────────────────────────────

BASE_DIR="${ARTIFACTS_DIR:-$(cd "$(dirname "$0")/.." && pwd)/artifacts}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
VALID_PERSONAS=("research-analyst" "financial-analyst" "dev" "operations-manager")

# ── Arg Parsing ──────────────────────────────────────────────────────────────

if [ $# -lt 3 ]; then
    echo "Usage: $0 <persona> <title> <content_file|->" >&2
    echo "Valid personas: ${VALID_PERSONAS[*]}" >&2
    exit 1
fi

PERSONA="$1"
TITLE="$2"
CONTENT_SRC="$3"
SOURCES="${SOURCES:-}"
EXECUTIVE_SUMMARY="${EXECUTIVE_SUMMARY:-}"
AUTHOR="${AUTHOR:-}"

# Auto-registration settings (Phase 2)
# Set AUTO_REGISTER=false to skip automatic vault registration after generation
AUTO_REGISTER="${AUTO_REGISTER:-true}"
REGISTER_STATUS="${REGISTER_STATUS:-draft}"
REGISTER_TAGS="${REGISTER_TAGS:-}"
REGISTER_FRESHNESS="${REGISTER_FRESHNESS:-90}"

# Validate persona
VALID=false
for p in "${VALID_PERSONAS[@]}"; do
    if [ "$p" = "$PERSONA" ]; then
        VALID=true
        break
    fi
done
if [ "$VALID" = false ]; then
    echo "Error: Invalid persona '$PERSONA'. Must be one of: ${VALID_PERSONAS[*]}" >&2
    exit 1
fi

# Set default author from persona if not overridden
if [ -z "$AUTHOR" ]; then
    case "$PERSONA" in
        research-analyst)   AUTHOR="Research Analyst" ;;
        financial-analyst)  AUTHOR="Financial Analyst" ;;
        dev)                AUTHOR="Dev" ;;
        operations-manager) AUTHOR="Operations Manager" ;;
    esac
fi

# ── Read Content ─────────────────────────────────────────────────────────────

if [ "$CONTENT_SRC" = "-" ]; then
    CONTENT=$(cat)
elif [ -f "$CONTENT_SRC" ]; then
    CONTENT=$(cat "$CONTENT_SRC")
else
    echo "Error: Content file '$CONTENT_SRC' not found" >&2
    exit 1
fi

if [ -z "$CONTENT" ]; then
    echo "Error: Content is empty" >&2
    exit 1
fi

# ── Generate Filename ────────────────────────────────────────────────────────

# Convert title to kebab-case for filename
KEBAB=$(echo "$TITLE" \
    | tr '[:upper:]' '[:lower:]' \
    | sed 's/[^a-z0-9]/-/g' \
    | sed 's/^-\+//; s/-\+$//' \
    | tr -s '-')
TIMESTAMP=$(date '+%Y-%m-%d')
FILENAME="${TIMESTAMP}_${KEBAB}.md"

# ── Write Artifact ───────────────────────────────────────────────────────────

PERSONA_DIR="${BASE_DIR}/${PERSONA}"
mkdir -p "$PERSONA_DIR"
OUTPUT_PATH="${PERSONA_DIR}/${FILENAME}"

{
    echo "# ${TITLE}"
    echo ""
    echo "## Executive Summary"
    echo ""
    if [ -n "$EXECUTIVE_SUMMARY" ]; then
        echo "${EXECUTIVE_SUMMARY}"
    else
        echo "*No executive summary provided.*"
    fi
    echo ""
    echo "## Main Content"
    echo ""
    echo "${CONTENT}"
    echo ""

    if [ -n "$SOURCES" ]; then
        echo "## Sources"
        echo ""
        echo "${SOURCES}"
        echo ""
    fi

    echo "## Generated By"
    echo ""
    echo "- **Persona:** ${AUTHOR}"
    echo "- **Timestamp:** $(date '+%Y-%m-%d %H:%M:%S UTC')"
} > "$OUTPUT_PATH"

# ── Verify ───────────────────────────────────────────────────────────────────

if [ -f "$OUTPUT_PATH" ] && [ -s "$OUTPUT_PATH" ]; then
    echo "$OUTPUT_PATH"
    
    # ── Auto-registration (Phase 2) ────────────────────────────────────────────
    if [ "$AUTO_REGISTER" = "true" ]; then
        REL_PATH="artifacts/${PERSONA}/${FILENAME}"
        REG_SCRIPT="${SCRIPT_DIR}/register-artifact.sh"
        
        if [ -f "$REG_SCRIPT" ]; then
            # Auto-generate tags from persona + title keywords if not explicitly set
            if [ -z "$REGISTER_TAGS" ]; then
                REGISTER_TAGS=$(echo "$TITLE" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9 ]//g' | tr ' ' ',')
                REGISTER_TAGS="${PERSONA}, ${REGISTER_TAGS}"
                REGISTER_TAGS=$(echo "$REGISTER_TAGS" | sed 's/,,*/,/g; s/^,//; s/,$//')
            fi
            
            # Derive summary from EXECUTIVE_SUMMARY or first line of content
            REG_SUMMARY="${EXECUTIVE_SUMMARY}"
            if [ -z "$REG_SUMMARY" ]; then
                REG_SUMMARY=$(echo "$CONTENT" | head -1 | sed 's/^#* //; s/^[[:space:]]*//; s/[[:space:]]*$//')
                [ ${#REG_SUMMARY} -gt 120 ] && REG_SUMMARY="${REG_SUMMARY:0:117}..."
            fi
            
            echo "→ Auto-registering in Knowledge Vault..."
            bash "$REG_SCRIPT" \
                --persona "$PERSONA" \
                --title "$TITLE" \
                --status "$REGISTER_STATUS" \
                --tags "$REGISTER_TAGS" \
                --freshness "$REGISTER_FRESHNESS" \
                --summary "$REG_SUMMARY" \
                --path "$REL_PATH" || echo "  [warn] Registration failed (non-fatal)" >&2
        else
            echo "  [warn] Registration script not found: ${REG_SCRIPT}" >&2
        fi
    fi
    
    exit 0
else
    echo "Error: Failed to write artifact" >&2
    exit 1
fi
